# Generated by Django 5.0.6 on 2024-12-23 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='work_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee_app.workarea', verbose_name='作業エリア'),
        ),
    ]
