# Generated by Django 5.0.6 on 2025-01-03 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_alter_customuser_work_area'),
        ('voc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='表彰種類')),
            ],
        ),
        migrations.CreateModel(
            name='AwardCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='従業員')),
                ('award_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.awardtype', verbose_name='表彰種類')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voc_app.work', verbose_name='工事')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='従業員')),
            ],
        ),
    ]
