# Generated by Django 5.0.6 on 2025-01-03 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='年代')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='性別')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.IntegerField(verbose_name='質問1')),
                ('question2', models.IntegerField(verbose_name='質問2')),
                ('question3', models.IntegerField(verbose_name='質問3')),
                ('question4', models.IntegerField(verbose_name='質問4')),
                ('question5', models.IntegerField(verbose_name='質問5')),
                ('free_text', models.TextField(blank=True, null=True, verbose_name='自由記入欄')),
                ('free_text_ai_rating', models.IntegerField(blank=True, null=True, verbose_name='自由記入欄AI評価')),
                ('submitted_at', models.DateField(auto_now_add=True, verbose_name='投稿日')),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voc_app.agegroup', verbose_name='年代')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voc_app.gender', verbose_name='性別')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.IntegerField(unique=True, verbose_name='受付番号')),
                ('receipt_date', models.DateTimeField(verbose_name='受付日')),
                ('work_start_date', models.DateField(verbose_name='作業開始日')),
                ('url_token', models.CharField(max_length=255, unique=True, verbose_name='URLトークン')),
                ('url_token_expiry', models.DateField(verbose_name='URLトークン期限')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voc_app.survey', verbose_name='アンケート')),
            ],
        ),
    ]
